title:            backspace.fm
tagline:          一週間分のテック・ガジェットニュースを配信するポッドキャスト
description:      一週間分のテック・ガジェットニュースを配信するポッドキャスト
logo:             site-logo.png
disqus_shortname: 
search:           false
keywords:         iPhone,iPad,Android,tech,gadget,technology,camera,tablet,internet,Apple,Google,news,San Francisco,ガジェット
feed:             http://feeds.backspace.fm/backspacefm
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://backspace.fm

# Owner/author information
author: Koichi Aoki
owner:
  name:           drikin, mazzo and yuka
  avatar:         bio-photo.png
  email:          drikin+backspacefm@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        backspacefm
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+BackspaceFmHome

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48511878-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: https://medium.com/backstage-of-backspace
    external: true
  - title: iTunes
    url: https://itunes.apple.com/jp/podcast/backspace.fm/id830709730
    external: true
  - title: Calendar
    url: https://www.google.com/calendar/embed?src=je3ul6a9tp9esq6efrouf1ht6c%40group.calendar.google.com&ctz=Japan/Tokyo
    external: true
  - title: Live
    url: /live.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: true
markdown:    redcarpet
safe:        true
lsi:         false

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
